project_id = "mfwyiifehsvwnjwqoxht"

[functions.check-password-breach]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-portal]
verify_jwt = true
