project_id = "mfwyiifehsvwnjwqoxht"

[functions.check-password-breach]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-portal]
verify_jwt = true

[functions.process-unit-states]
verify_jwt = false

[functions.sensor-simulator]
verify_jwt = true

[functions.check-missed-logs]
verify_jwt = false

[functions.export-temperature-logs]
verify_jwt = false

[functions.process-escalations]
verify_jwt = false
